### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by mobileonekh** [DoubangoTelecom/tesseractMRZ#1]
Hi, can you provide your Web source code?

THanks;

**Comment by DoubangoTelecom** [comment]
What do you mean by "Web source code"? This repo is about training data. You already have ready-to use tesseract models in the repo (tessdata_*)

**Comment by mobileonekh** [comment]
Thanks for your response.
We try your training data with tesseract version 4. But the result is not as good as your https://www.doubango.org/webapps/mrz/

So my guess is your configuration is different.

Regards;
Chamroeun

**Comment by DoubangoTelecom** [comment]
We're using the same models on our servers. Off course you've to clean up the MRZ zone and binarize it before passing it to Tesseract. You've to deskew and deslant the lines. Do you have sample images?
