### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by Eitol** [DoubangoTelecom/tesseractMRZ#2]
Hi, can you upload the script you used to train the network?

I have a dataset of approximately 14 million real images of identity card fields with their respective text (gt.txt). It includes 1.4 million MRZ fields.
The data was validated and was not generated synthetically so it may be better for real scenarios.

I can share the training result with you without problems.
Thanks in advance

**Comment by DoubangoTelecom** [comment]
Hello, 
For the training please check https://groups.google.com/forum/#!topic/doubango-ai/8KgjmbFyAl4
Yes, if you can share the dataset it would be helpful for us to improve the model. With such amount of data it would be possible to replace Tesseract with a deep learning OCR model coupled with an  attention layer

**Comment by xxxpsyduck** [comment]
@Eitol Hello. How is the result? Can you share the trained model with us?
