### ISSUE TITLE
Passport numbers starting with character 'O'

### ISSUE THREAD

**Issue by prats0305** [DoubangoTelecom/tesseractMRZ#5]
Hi, I am trying to use traineddata but have noticed a very peculiar issue for passport images where the passport number starts with 'O' are getting read as '0' (zero). However, other O's in the mrz section are getting read correctly. PP number - 'O996479' getting read as - '0996479'. How can I fix this ?
![TestCropped](https://user-images.githubusercontent.com/7957884/104172770-33381e80-541e-11eb-9d71-983937971fc3.jpg)

**Comment by DoubangoTelecom** [comment]
You'll need to retrain the model with your own data
